theme = "dracula"

[editor]
program = "vi"
args = []

[fonts]
size = 18
features = []
use-drawable-chars = true
symbol-map = []
disable-warnings-not-found = false
additional-dirs = []

[fonts.regular]
family = "JetBrains Mono"
style = "Normal"
width = "Normal"
weight = 400

[fonts.bold]
family = "JetBrains Mono"
style = "Normal"
width = "Normal"
weight = 800

[fonts.italic]
family = "JetBrains Mono"
style = "Italic"
width = "Normal"
weight = 400

[fonts.bold-italic]
family = "JetBrains Mono"
style = "Italic"
width = "Normal"
weight = 800

[colors]
# This is a basic "One Dark" style palette
background = '#282c34'
foreground = '#abb2bf'
cursor = '#528bff'
tabs = '#282c34'
tabs-active = '#528bff'

[cursor]
shape = 'block'
